### ISSUE TITLE
Large amount of results

### ISSUE THREAD

**Issue by tanyafilo** [MirazMac/GoogleCSEScrapper#1]
Hey, may you help me with my own issue?
I'm trying to scrape large amount of results in Google, but I reach a limit of XXX with the message :

"In order to show you the most relevant results, we have omitted some entries very similar to the XXX already displayed.
If you like, you can repeat the search with the omitted results included."

I'm trying to get through 1000 results.
Any advises? clues?
Thanks ahead.

**Comment by MirazMac** [comment]
Sorry but there's a built in limit on the free version of Google CSE, you can't bypass the enforced limit with this scrapper. At least not anything that I know of.

**Comment by tanyafilo** [comment]
ohh
thanks!

may you recommend other good scrappers?  or a manual one?

**Comment by MirazMac** [comment]
This is one of the reliable ones, the other scrappers that tries to scrape from the Google results page would very likely get a captcha in within 2-3 request or even in the first one. So, I don't know any reliable scrapper as of this moment. I'm so sorry but I don't have anything for you in this matter.
